In [41]:
import tensorflow as tf

## Adição

In [42]:
tensor_soma = tf.add(1,2)

In [43]:
type(tensor_soma)

tensorflow.python.framework.ops.Tensor

In [44]:
print(tensor_soma)

Tensor("Add_3:0", shape=(), dtype=int32)


In [45]:
sess = tf.Session()
resultado = sess.run(tensor_soma)
sess.close()

In [46]:
print(type(resultado))
print(resultado)

<class 'numpy.int32'>
3


## Subtração

In [47]:
tensor_sub = tf.subtract(20,2)
print(type(tensor_sub))
print(tensor_sub)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Sub_1:0", shape=(), dtype=int32)


In [48]:
with tf.Session() as sess:
    resultado = sess.run(tensor_sub)
    
print(type(resultado))
print(resultado)

<class 'numpy.int32'>
18


# Constantes do tipo escalar

In [49]:
a = tf.constant(50.5)
b = tf.constant(10.)

tensor_add = tf.add(a,b)

In [50]:
type(a)

tensorflow.python.framework.ops.Tensor

In [51]:
print(a)

Tensor("Const_6:0", shape=(), dtype=float32)


In [52]:
with tf.Session() as sess:
    resultado = sess.run(tensor_add)

type(resultado)
print(resultado)

60.5


# Constantes textuais(escalar)

In [53]:
t1 = tf.constant('ola ')
t2 = tf.constant('mundo')

In [54]:
type(t1)

tensorflow.python.framework.ops.Tensor

In [55]:
print(t1)

Tensor("Const_8:0", shape=(), dtype=string)


In [56]:
with tf.Session() as sess:
    t3 = sess.run(t1 + t2)

In [57]:
print(t3)

b'ola mundo'


## Mesclando as operanções

In [58]:
a = tf.constant(1)
b = tf.constant(2)
print(a)
print(b)

Tensor("Const_10:0", shape=(), dtype=int32)
Tensor("Const_11:0", shape=(), dtype=int32)


In [70]:
a = tf.constant(2., name = 'const_a')
b = tf.constant(2., name = 'const_b')
print(a)
print(b)

Tensor("const_a_2:0", shape=(), dtype=float32)
Tensor("const_b_2:0", shape=(), dtype=float32)


In [71]:
t_add = tf.add(a,b, name = 'op_add_a') # = 4

t_mult = tf.multiply(a,b, name = 'ap_mult_a') # = 4

t_pow = tf.pow(t_add,t_mult, name = 'ap_pow_a') # = 4^4

In [72]:
with tf.Session() as sess:
    saida = sess.run(t_pow)
print(saida)

256.0


### mais de uma operação

In [73]:
tensor_mult2 = tf.multiply(a,tensor_add)
print(tensor_mult2)

Tensor("ap_mult_b_1:0", shape=(), dtype=float32)


In [75]:
with tf.Session() as sess:
    saida1, saida2 = sess.run([t_pow, tensor_mult2])
print(saida1)
print(saida2)

256.0
121.0


# váriaveis

In [76]:
a = tf.Variable(2, name = 'variable_a')
b = tf.Variable(2, name = 'variable_b')

tensor_add = tf.add(a,b)

In [77]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tensor_add))


4


## Vetores

In [78]:
t_vertorzao = tf.constant([1,2,3])
print(type(t_vertorzao))
print(t_vertorzao)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("vertorzao_2:0", shape=(3,), dtype=int32)


In [79]:
tensor_add = tf.Variable(t_vertorzao + 10)

In [80]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tensor_add))

[11 12 13]


## Matrizes

In [81]:
t_matriz_a = tf.constant([[1,2,3],
                         [3,2,1]])

t_matriz_b = tf.constant([[1,2,3],
                         [3,2,1]])

In [82]:
print(type(t_matriz_a))
print(t_matriz_a)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("matriz_a_1:0", shape=(2, 3), dtype=int32)


In [83]:
tensor_mult = tf.Variable(t_matriz_a * t_matriz_b)

In [87]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tensor_mult))

[[1 4 9]
 [9 4 1]]


In [92]:
tensor_mult2 = tf.multiply(t_matriz_a,t_matriz_b)
print(tensor_mult2)

Tensor("mult_m_1:0", shape=(2, 3), dtype=int32)


In [93]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tensor_mult2))

[[1 4 9]
 [9 4 1]]


In [ ]:
# tensor_mult3 = tf.matmul(t_matriz_a,t_matriz_b, name = 'matmult_m')

In [99]:
t_matriz_a1 = tf.constant([[1,2],
                          [3,2]])

t_matriz_b1 = tf.constant([[1,2],
                          [3,2]])

tensor_mult3 = tf.matmul(t_matriz_a1,t_matriz_b1)

In [100]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tensor_mult3))

[[ 7  6]
 [ 9 10]]


In [91]:
t_matriz_b.shape

TensorShape([Dimension(2), Dimension(3)])

## Manipulando variaveis entre sessões

In [29]:
a = tf.Variable(2, name = 'variavel_a')


In [35]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for i in range(3):
        a = a + 1
        print(sess.run(a))
        


9
10
11


## Placeholders

In [109]:
placeholder = tf.placeholder('int32')
placeholder = tf.placeholder(tf.int32)
print(type(placeholder))
print(placeholder)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Placeholder_5:0", dtype=int32)


In [107]:
add = placeholder + 5

with tf.Session() as sess:
#     sess.run(add)
 saida = sess.run(add, feed_dict= { placeholder: 10 })
print(saida)        

15


In [ ]:
placeholder = tf.placeholder('int32')
placeholder = tf.placeholder(tf.int32)
print(type(placeholder))
print(placeholder)

In [ ]:
add = placeholder + 1

with tf.Session() as sess:
    saida = sess.run(add, feed_dict= { placeholder: [0,2,5] })
print(saida)  

In [113]:
# placeholder = tf.placeholder(tf.int32, 2)
placeholder = tf.placeholder(tf.int32, [2,2])
placeholder = tf.placeholder(tf.int32, [None,2])

add = placeholder + 1

with tf.Session() as sess:
#     data = [0,2,5]
    data = [[0,2],
            [0,2],
            [0,2]]
    saida = sess.run(add, feed_dict= { placeholder: data })
print(saida)  


ValueError: Cannot feed value of shape (3,) for Tensor 'Placeholder_9:0', which has shape '(1, 3)'